<?php
require_once __DIR__ . '/api/auth.php';
require_auth();
require_permission('view-reports');
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Saved Reports | The Absolute Essential</title>
  <link rel="stylesheet" href="assets/styles.css" />
  <link rel="icon" href="assets/icons/absoluteessential-fav-teal.png" type="image/x-icon">
</head>
<body class="page-dash">
  <?php include __DIR__ . '/includes/sidebar.php'; ?>

  <div class="main">
    <div class="page-header">
      <div>
        <h2>Saved Reports</h2>
        <p class="subtitle">Reports generated by analysts.</p>
      </div>
    </div>

    <div class="data-table-wrap" style="margin-top:20px;">
      <table class="data-table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Source</th>
            <th>Date Range</th>
            <th>Author</th>
            <th>Created</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody id="reports-tbody">
          <tr><td colspan="6" class="empty-state">Loading...</td></tr>
        </tbody>
      </table>
    </div>

    <!-- Report viewer modal -->
    <div id="report-viewer" style="display:none; position:fixed; inset:0; background:rgba(0,0,0,0.5); z-index:300; overflow-y:auto;">
      <div style="max-width:1000px; margin:40px auto; background:#fff; border-radius:12px; padding:30px; position:relative;">
        <button onclick="closeViewer()" style="position:absolute; top:16px; right:16px; border:none; background:#eee; border-radius:8px; padding:8px 14px; cursor:pointer; font-weight:600;">Close</button>
        <div id="report-viewer-content"></div>
      </div>
    </div>
  </div>

  <script>
    function esc(s) { const d=document.createElement('div'); d.textContent=s; return d.innerHTML; }
    const canDelete = <?= has_permission('create-reports') ? 'true' : 'false' ?>;

    async function loadReports() {
      const tbody = document.getElementById('reports-tbody');
      try {
        const r = await fetch('api/reports.php');
        const reports = await r.json();

        if (!reports.length) {
          tbody.innerHTML = '<tr><td colspan="6" class="empty-state">No saved reports yet.</td></tr>';
          return;
        }

        tbody.innerHTML = '';
        reports.forEach(rpt => {
          const tr = document.createElement('tr');
          const dateRange = (rpt.date_from || '?') + ' — ' + (rpt.date_to || '?');
          const created = (rpt.created_at || '').substring(0, 10);

          let actions = '<button class="filter-btn" onclick="viewReport(' + rpt.id + ')">Preview</button> ';
          actions += '<button class="filter-btn" onclick="openFullReport(' + rpt.id + ')">Open</button>';
          if (canDelete) {
            actions += ' <button class="remove-btn" onclick="deleteReport(' + rpt.id + ')">Delete</button>';
          }

          tr.innerHTML =
            '<td>' + esc(rpt.title) + '</td>' +
            '<td><span class="tag-type">' + esc(rpt.source) + '</span></td>' +
            '<td class="mono">' + esc(dateRange) + '</td>' +
            '<td>' + esc(rpt.author || '—') + '</td>' +
            '<td class="mono">' + esc(created) + '</td>' +
            '<td>' + actions + '</td>';
          tbody.appendChild(tr);
        });
      } catch(e) {
        tbody.innerHTML = '<tr><td colspan="6" class="empty-state" style="color:#c0392b;">Failed to load reports.</td></tr>';
      }
    }

    async function viewReport(id) {
      try {
        const r = await fetch('api/reports.php?id=' + id);
        const rpt = await r.json();
        if (rpt.error) { alert(rpt.error); return; }

        const viewer = document.getElementById('report-viewer');
        const content = document.getElementById('report-viewer-content');

        let kpiData = rpt.kpi_data;
        if (typeof kpiData === 'string') try { kpiData = JSON.parse(kpiData); } catch { kpiData = {}; }
        let chartImages = rpt.chart_images;
        if (typeof chartImages === 'string') try { chartImages = JSON.parse(chartImages); } catch { chartImages = {}; }

        let html = '';
        html += '<h1 style="font-size:22px; margin-bottom:4px;">' + esc(rpt.title) + '</h1>';
        html += '<div style="color:#666; font-size:13px; margin-bottom:16px;">';
        html += 'Date Range: ' + esc((rpt.date_from||'') + ' — ' + (rpt.date_to||''));
        html += ' · Author: ' + esc(rpt.author || '—');
        html += ' · Created: ' + esc((rpt.created_at||'').substring(0,10));
        html += '</div>';

        if (rpt.comment) {
          html += '<div style="background:#f8f8f8; border-radius:8px; padding:14px; margin-bottom:20px;">';
          html += '<h3 style="font-size:14px; margin-bottom:6px; color:#666;">Analyst Commentary</h3>';
          html += '<p style="white-space:pre-wrap; margin:0; color:#1a1a1a;">' + esc(rpt.comment) + '</p>';
          html += '</div>';
        }

        // KPIs
        if (kpiData && Object.keys(kpiData).length) {
          html += '<div style="display:grid; grid-template-columns:repeat(4,1fr); gap:12px; margin-bottom:20px;">';
          for (const [label, value] of Object.entries(kpiData)) {
            html += '<div style="border:1px solid #eee; border-radius:8px; padding:12px; text-align:center;">';
            html += '<div style="font-size:11px; color:#666; text-transform:uppercase;">' + esc(label) + '</div>';
            html += '<div style="font-size:22px; font-weight:700;">' + esc(value) + '</div>';
            html += '</div>';
          }
          html += '</div>';
        }

        // Charts
        if (chartImages && Object.keys(chartImages).length) {
          html += '<div style="display:grid; grid-template-columns:1fr 1fr; gap:16px; margin-bottom:20px;">';
          for (const [id, src] of Object.entries(chartImages)) {
            html += '<div style="border:1px solid #eee; border-radius:8px; padding:12px; text-align:center;">';
            html += '<img src="' + src + '" style="max-width:100%; height:auto;" />';
            html += '</div>';
          }
          html += '</div>';
        }

        // Tables
        if (rpt.table_html) {
          html += rpt.table_html;
        }

        content.innerHTML = html;
        viewer.style.display = 'block';
      } catch(e) {
        alert('Failed to load report');
      }
    }

    function closeViewer() {
      document.getElementById('report-viewer').style.display = 'none';
    }

    document.getElementById('report-viewer')?.addEventListener('click', function(e) {
      if (e.target === this) closeViewer();
    });
    document.addEventListener('keydown', e => { if (e.key === 'Escape') closeViewer(); });

    async function deleteReport(id) {
      if (!confirm('Delete this report?')) return;
      await fetch('api/reports.php?id=' + id, { method: 'DELETE' });
      loadReports();
    }

    loadReports();

    function openFullReport(id) {
      window.open('view-report.php?id=' + id, '_blank');
    }
  </script>
</body>
</html>